# Add 'documentation' label to any change to *.md files
documentation:
- any: ['**/*.md']

# Add 'docker' label to any change in docker related files
docker:
- any: ['**/Dockerfile*', '**/.dockerignore']

# Add 'github_actions' label to any change .github/ directory
test_adami_xx:
- any: ['.github/**']

# Add 'go' label to any change *.go files
go:
- any: ['**/*.go']


